export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_DEPOSIT_AMOUNT = "SET_DEPOSIT_AMOUNT";
export const SET_INTEREST_RATE = "SET_INTEREST_RATE";

export const SET_TAB_VALUE = "SET_TAB_VALUE";
export const SET_BUY_SELL_TAB = "SET_BUY_SELL_TAB";
export const SET_MY_ORDER_TYPE_SELECTED = "SET_MY_ORDER_TYPE_SELECTED";
export const SET_MY_OR_GLOBAL = "SET_MY_OR_GLOBAL";

export const SET_ALL_TOKENS = "SET_ALL_TOKENS";
export const SET_CURR_REF_TOKEN = "SET_CURR_REF_TOKEN";
export const SET_CURR_AGAINST_TOKEN = "SET_CURR_AGAINST_TOKEN";

export const LOG_MESSAGE = "LOG_MESSAGE";
export const IS_MESSAGE_DISPLAY = "IS_MESSAGE_DISPLAY";

// export const SET_ROWS_BUY_MYORDER = "SET_ROWS_BUY_MYORDER";
// export const SET_ROWS_SELL_MYORDER = "SET_ROWS_SELL_MYORDER";

export const SET_ROWS_BUY_GLOBALORDER = "SET_ROWS_BUY_GLOBALORDER";
export const SET_ROWS_SELL_GLOBALORDER = "SET_ROWS_SELL_GLOBALORDER";

export const SET_USER_BUY_ORDERS = "SET_USER_BUY_ORDERS";
export const SET_USER_SELL_ORDERS = "SET_USER_SELL_ORDERS";
export const SET_USER_FILLED_ORDERS = "SET_USER_FILLED_ORDERS";
export const SET_IS_ANY_ORDER_CANCELLED = "SET_IS_ANY_ORDER_CANCELLED";
export const SET_GLOBAL_ORDERS = "SET_GLOBAL_ORDERS";
export const INC_ORDER_COUNT = "INC_ORDER_COUNT";
