export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_DEPOSIT_AMOUNT = "SET_DEPOSIT_AMOUNT";

export const SET_TAB_VALUE = "SET_TAB_VALUE";
export const SET_BUY_SELL_TAB = "SET_BUY_SELL_TAB";

export const SET_ALL_TOKENS = "SET_ALL_TOKENS";
export const SET_CURR_REF_TOKEN = "SET_CURR_REF_TOKEN";
export const SET_CURR_AGAINST_TOKEN = "SET_CURR_AGAINST_TOKEN";
